# change this to your app id
application: static-site-seed
version: 1
runtime: go
api_version: go1

handlers:

  - url: /$
    static_files: app/index.html
    upload: app/index.html

  - url: /bower_components
    static_dir: bower_components

  - url: /
    static_dir: app

# Recommended file skipping declaration from the GAE tutorials
skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?tests$
  - ^(.*/)?test$
  - ^test/(.*/)?
  - ^COPYING.LESSER
  - ^README\..*
  - \.gitignore
  - ^\.git/.*
  - \.*\.lint$
  - ^fabfile\.py
  - ^testrunner\.py
  - ^grunt\.js
  - ^node_modules/(.*/)?
  - ^tags$
  - *\.swp$
  - *\.swap$
  - ^session.vim$
  - ^\/\.tmp
  - (.*).sass
  - (.*).ts


